#!/usr/bin/env python3
"""Write one regression case per command that no shipped example exercises.

smoke2.py records, in smoke2_cache.json, the fixture and argument shape that
made each command run.  That is exactly the recipe a regression case needs, so
the cases are generated from it rather than written by hand -- and the fixtures
are imported from smoke2 rather than copied, so the two cannot drift apart.

The shipped examples exercise 93 of the 272 commands.  This fills in the rest.
References come from the current binary, so they pin behaviour against future
change; they say nothing about whether that behaviour is correct.

Usage: python3 tools/make_tests.py [outdir]   (default examples/tests)
"""
import json, re, sys, shutil
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "tests"))
sys.argv = [sys.argv[0]]            # smoke2 reads argv; give it nothing
import smoke2

HERE = Path(__file__).parent
ROOT = HERE.parent
out = Path(sys.argv[1] if len(sys.argv) > 1 else ROOT / "examples" / "tests")
out.mkdir(parents=True, exist_ok=True)

# The fixtures smoke2 built in its temporary directory are what the cases need.
# Third-party input files are not copied into the suite: they are not ours to
# redistribute, so the commands that read them are left out unless
# TDA_EXT_INPUT points at a directory holding them.
ext_names = set()
if smoke2.HAVE_EXT:
    ext_names = {f.name for f in smoke2.EXT.iterdir() if f.is_file()}

for f in Path(smoke2.work).iterdir():
    if f.is_file() and f.suffix != ".cf" and f.name not in ext_names:
        shutil.copy(f, out / f.name)

cache = json.loads((ROOT / "tests" / "smoke2_cache.json").read_text())

# Commands whose output on the generic fixture data is not reproducible across
# platforms, so a reference captured from one build is worthless.  These are
# not TDA bugs and not skipped for convenience: the fixture data is simply
# unsuitable for them, and pinning the result would only assert that every
# platform produces the same undefined answer.
#
#   ivreg2   the likelihood is undefined on this data -- Linux gcc prints
#            "Best function value: -nan", clang prints 0.00000000
#   indep    counts depend on the order equal keys come out of the sort
#   mdsn     scaling order, likewise
#   nmca     the cycle it reports depends on tie order
#   sdcpol   segment/polygon assignment depends on tie order
UNSTABLE = {"ivreg2", "indep", "mdsn", "nmca", "sdcpol",
            # These three write a text file and then report its size or dump
            # its bytes.  TDA writes text files through OPEN_WR, which is "w"
            # -- text mode -- so on Windows the lines end CRLF and every count
            # is one byte per line larger than on Linux.  See the note in
            # tda.h: making TDA write LF everywhere would make these portable,
            # but it changes what users get in their output files.
            "dsplit", "dump", "rplz"}

# Commands the shipped examples already cover.
used = set()
for suite in ("exam", "ehhnew"):
    d = ROOT / "examples" / suite
    if not d.is_dir():
        continue
    for cf in d.glob("*.cf"):
        txt = re.sub(r"#.*", "", cf.read_text(errors="replace"))
        for stmt in txt.split(";"):
            m = re.match(r"\s*([a-z][a-z0-9_]*)\s*[(=]?", stmt)
            if m:
                used.add(m.group(1))

written, skipped, external, unstable = 0, 0, 0, 0
for cmd in sorted(cache):
    if cmd in used:
        skipped += 1
        continue
    pname, form = cache[cmd]
    pre = smoke2.PRELUDE.get(pname)
    if pre is None:
        skipped += 1
        continue
    # Cases that read a third-party file are only written when that file is
    # actually present; they are not distributable.
    if not smoke2.HAVE_EXT and cmd in smoke2.EXT_ONLY:
        external += 1
        continue
    if cmd in UNSTABLE:
        unstable += 1
        continue
    (out / (cmd + ".cf")).write_text(
        "# %s.cf -- generated by make_tests.py from the smoke cache\n"
        "# fixture: %s\n\n%s%s\n" % (cmd, pname, pre, form % cmd))
    (out / (cmd + ".ref")).touch(exist_ok=True)
    written += 1

print("wrote %d cases, skipped %d (already covered), %d need external input, "
      "%d not reproducible across platforms" % (written, skipped, external, unstable))
