#!/bin/bash

rm gsoep.s
rm gsoep18.v*
rm gsoep18.zoo
rm gsoep18.bak

echo 'gsoep18.zoo' > gsoep18.s

FN=1

for f in *.por ; do
    tda "rspss(ns=1,dvara(fn="${FN}")=gsoep18.v,arcda=gsoep18.s,df="${f/por/dat}")="${f} ;
    zoo ah gsoep18 ${f/por/dat};
    rm ${f/por/dat};
    FN=$((1+FN))          
done  

tda "arcvc(df=gsoep18.var)=gsoep18.v"
zoo ah gsoep18 gsoep18.var
echo 999 gsoep18.var  2   0 `cat gsoep18.var | wc -l `  0 >> gsoep18.s
zoo ah gsoep18 gsoep18.s
zoo PP gsoep18
