# makefile for tda 
# note: check tda.h for basic adjustments.
  
# define the C compiler

CC = gcc 

# Define compiler flags. NOTE: the program should be compiled with
# a global signed char.
# CFLAGS = +p +w 
  CFLAGS =  -O2 -fsigned-char

# In the following LIB statement, -lm is necessary to include the math
# library. -lX11 is required if S_XWIN is set in tda.h in order to
# include the X11 library.
LIB = -lm -L/usr/X11R6/lib -lX11    
# LIB = -lm -lX11    

#define the destination directory for the executable tda
DESTDIR = 
  
#List of all object files for tda
TDA_O      = tda.o  \
	t_cmd.o t_gen.o t_rep.o t_help.o \
	t_eval.o t_eval1.o t_eval2.o t_eval3.o t_brr.o \
	t_rand.o t_gf.o t_cdf.o t_gdf.o t_loglin.o \
	t_parm.o t_pgen.o t_alloc.o t_sort.o t_con.o t_gcmd.o \
	t_dmu.o t_int.o \
	t_gdat.o t_var.o t_mdat.o t_pdat.o \
	t_rzoo.o t_zoo.o t_spss.o t_stata.o  \
	t_dstat.o t_ds.o t_freq.o t_spl.o t_smo.o t_dens.o t_ineq.o \
	t_lsreg.o t_l1reg.o t_areg.o t_glm.o t_nlreg.o \
	t_mat.o t_matc.o t_matf.o t_svd.o t_lin.o t_lsei.o \
	t_imat.o \
	t_lp.o t_qrmod.o t_fnqr.o \
	t_gmin.o t_tmin.o t_ml.o t_min.o  \
	t_edat.o t_ltb.o t_ple.o \
	t_rate.o t_prate.o t_fnrta.o t_fnrtb.o t_fnrtc.o \
	t_seq.o t_seqe.o t_seqm.o  \
	t_psf.o t_plot.o t_dplot.o t_psinit.o t_cplot.o \
	t_plg.o t_xplot.o \
	t_gdd.o t_graph.o t_gio.o t_tree.o t_gg.o t_prox.o t_cl.o \
	t_mds.o t_com.o t_ass.o t_mes.o t_dem.o t_xwin.o

all :   
	@echo "There is no default. Possible targets are as follows:"  
	@echo ' '  
	@echo "tda:       tda"  
  
tda: $(TDA_O)  
	$(CC) $(CFLAGS) $(TDA_O) $(LIB) -o $(DESTDIR)tda  

#######################################################################  
# Dependencies  
  
tda.o       : tda.c tda.h t_cmd.h t_gen.h t_mat.h t_var.h t_eval.h t_rep.h  
t_cmd.o     : t_cmd.c tda.h t_gen.h t_pgen.h t_var.h t_gdat.h t_gcmd.h \
	      t_mat.h t_matf.h t_dmu.h t_mdat.h t_pdat.h t_rzoo.h t_spss.h \
	      t_stata.h t_psf.h t_lsreg.h t_l1reg.h t_qrmod.h t_dem.h \
	      t_edat.h t_ltb.h t_ple.h t_rate.h t_seq.h t_gmin.h t_int.h \
	      t_dstat.h t_ineq.h t_eval.h t_eval3.h t_dplot.h  t_plg.h t_smo.h \
	      t_glm.h t_gdd.h t_graph.h t_gio.h t_tree.h t_nlreg.h t_loglin.h \
	      t_xplot.h t_rep.h t_help.h t_gf.h t_brr.h t_gdf.h t_xwin.h \
	      t_gg.h t_com.h t_prox.h t_cl.h t_mds.h t_ass.h t_imat.h t_mes.h
t_xwin.o    : t_xwin.c tda.h t_gen.h t_pgen.h t_parm.h t_alloc.h t_plot.h \
	      t_ml.h t_gf.h
t_help.o    : t_help.c tda.h t_gen.h t_gf.h t_pgen.h
t_rep.o     : t_rep.c tda.h t_cmd.h t_gen.h t_pgen.h t_parm.h t_alloc.h \
	      t_var.h t_mat.h t_matf.h t_matc.h t_gf.h
t_dmu.o     : t_dmu.c tda.h t_gen.h t_pgen.h t_parm.h t_alloc.h \
	      t_freq.h t_gdat.h t_gf.h t_sort.h
t_gcmd.o    : t_gcmd.c tda.h t_gen.h t_pgen.h t_parm.h t_eval.h t_gdat.h \
	      t_gf.h t_var.h 
t_sort.o    : t_sort.c tda.h t_gen.h t_pgen.h t_parm.h t_gdat.h t_var.h
t_parm.o    : t_parm.c tda.h t_gen.h t_pgen.h t_var.h t_gmin.h t_gdat.h \
	      t_alloc.h t_eval.h t_plot.h t_ml.h t_mat.h t_rand.h t_imat.h \
	      t_gf.h
t_pgen.o    : t_pgen.c tda.h t_gen.h t_parm.h t_gdat.h t_eval.h t_eval1.h \
	      t_var.h t_cdf.h t_qrmod.h t_gf.h 
t_alloc.o   : t_alloc.c tda.h t_gen.h t_pgen.h t_parm.h
t_gen.o     : t_gen.c tda.h t_var.h
t_int.o     : t_int.c tda.h t_gen.h t_pgen.h t_parm.h t_alloc.h  \
	      t_gmin.h t_fnrtb.h t_gf.h t_eval.h t_eval3.h
t_rand.o    : t_rand.c tda.h t_gen.h t_pgen.h t_lin.h
t_gf.o      : t_gf.c tda.h t_gen.h
t_brr.o     : t_brr.c tda.h t_gen.h t_pgen.h t_gf.h t_alloc.h t_parm.h
t_cdf.o     : t_cdf.c tda.h t_gen.h t_gf.h t_lin.h

t_var.o     : t_var.c tda.h t_gen.h t_pgen.h t_eval.h t_gdat.h t_eval2.h \
	      t_parm.h t_gf.h t_alloc.h t_freq.h t_mdat.h t_eval3.h t_mat.h
t_gdat.o    : t_gdat.c tda.h t_gen.h t_pgen.h t_parm.h t_var.h \
	      t_gf.h t_zoo.h t_rzoo.h t_sort.h t_mdat.h t_pdat.h t_alloc.h \
	      t_rand.h t_eval.h t_eval1.h t_eval2.h t_eval3.h
t_mdat.o    : t_mdat.c tda.h t_gen.h t_pgen.h t_parm.h t_gdat.h \
	      t_var.h t_gf.h t_edat.h t_seq.h t_alloc.h t_gdd.h t_matf.h \
	      t_eval.h t_eval1.h t_mat.h t_matc.h t_rzoo.h
t_rzoo.o    : t_rzoo.c tda.h t_gen.h t_pgen.h t_parm.h t_zoo.h t_var.h \
	      t_gdat.h t_alloc.h t_gf.h
t_zoo.o     : t_zoo.c tda.h t_gen.h t_rzoo.h
t_spss.o    : t_spss.c tda.h t_gen.h t_pgen.h t_parm.h t_sort.h t_var.h \
	      t_gdat.h t_alloc.h t_eval.h t_eval1.h t_gf.h
t_stata.o   : t_stata.c tda.h t_gen.h t_pgen.h t_var.h t_gdat.h t_parm.h \
	      t_alloc.h t_sort.h t_eval.h t_eval1.h t_gf.h t_spss.h
t_pdat.o    : t_pdat.c tda.h t_gen.h t_pgen.h t_parm.h t_gdat.h \
	      t_var.h t_gf.h t_alloc.h t_sort.h

t_dstat.o   : t_dstat.c tda.h t_gen.h t_pgen.h t_parm.h t_alloc.h  \
	      t_gdat.h t_var.h t_ds.h t_sort.h t_freq.h t_gf.h t_cdf.h \
	      t_matf.h t_svd.h
t_ds.o      : t_ds.c tda.h t_gen.h t_pgen.h t_parm.h t_alloc.h \
	      t_var.h t_gdat.h t_sort.h t_cdf.h  
t_freq.o    : t_freq.c tda.h t_gen.h t_pgen.h t_gdat.h
t_ineq.o    : t_ineq.c tda.h t_gen.h t_pgen.h t_parm.h t_gdat.h t_alloc.h \
	      t_var.h t_ds.h t_matf.h
t_dens.o    : t_dens.c tda.h t_gen.h t_pgen.h t_parm.h t_gdat.h \
	      t_var.h t_plot.h t_alloc.h t_cdf.h
t_smo.o     : t_smo.c tda.h t_gen.h t_pgen.h t_parm.h t_alloc.h \
	      t_gdat.h t_var.h t_spl.h t_sort.h t_ml.h t_gf.h t_areg.h \
	      t_plot.h
t_spl.o     : t_spl.c tda.h t_gen.h          

t_gdf.o     : t_gdf.c tda.h t_gen.h t_pgen.h t_parm.h t_alloc.h t_svd.h \
	      t_gdat.h t_var.h t_con.h t_cdf.h t_lsei.h t_mat.h t_sort.h \
	      t_ml.h t_gf.h t_freq.h
t_lsreg.o   : t_lsreg.c tda.h t_gen.h t_pgen.h t_parm.h t_alloc.h t_svd.h \
	      t_gdat.h t_var.h t_con.h t_cdf.h t_lsei.h t_mat.h t_sort.h \
	      t_ml.h t_gf.h t_freq.h t_matf.h
t_l1reg.o   : t_l1reg.c tda.h t_gen.h t_pgen.h t_alloc.h t_var.h t_gdat.h \
	      t_parm.h t_gf.h t_sort.h t_lsei.h t_mat.h t_matf.h
t_areg.o    : t_areg.c tda.h t_gen.h t_pgen.h t_parm.h t_alloc.h t_gdat.h \
	      t_var.h t_sort.h t_ds.h t_smo.h t_gf.h
t_nlreg.o    : t_nlreg.c tda.h t_gen.h t_pgen.h t_parm.h t_gdat.h t_eval.h \
	      t_alloc.h t_ml.h t_gf.h t_var.h t_lin.h t_cdf.h t_eval3.h
t_glm.o     : t_glm.c tda.h t_gen.h t_pgen.h t_parm.h t_gdat.h t_eval.h \
	      t_alloc.h t_ml.h t_gmin.h t_lsei.h t_gf.h t_var.h t_con.h \
	      t_cdf.h t_eval3.h
t_qrmod.o   : t_qrmod.c tda.h t_gen.h t_pgen.h t_parm.h t_gdat.h t_freq.h \
	      t_ml.h t_gf.h t_var.h t_cdf.h t_con.h t_alloc.h \
	      t_sort.h t_min.h t_fnqr.h
t_fnqr.o    : t_fnqr.c tda.h t_gen.h t_gdat.h t_qrmod.h t_ml.h \
	      t_gf.h t_cdf.h t_lin.h t_int.h t_parm.h t_mat.h t_matf.h

t_mat.o     : t_mat.c tda.h t_gen.h t_var.h t_gdat.h t_matf.h t_gcmd.h \
	      t_pgen.h t_parm.h t_gf.h t_alloc.h t_matc.h t_imat.h t_gdd.h \
	      t_mdat.h
t_matc.o    : t_matc.c tda.h t_gen.h t_var.h t_gdat.h t_svd.h t_eval.h \
	      t_lin.h t_lsei.h t_lp.h t_pgen.h t_parm.h t_gf.h t_alloc.h \
	      t_mat.h t_matf.h t_sort.h t_brr.h
t_matf.o    : t_matf.c tda.h t_gen.h t_var.h t_gdat.h t_svd.h  \
	      t_lin.h t_lsei.h t_lp.h t_pgen.h t_parm.h t_gf.h t_alloc.h \
	      t_mat.h t_matc.h t_eval.h t_eval1.h t_eval2.h
t_imat.o    : t_imat.c tda.h t_gen.h t_var.h t_gdat.h t_mat.h t_matf.h  \
	      t_pgen.h t_parm.h t_gf.h t_alloc.h t_matc.h t_sort.h \
	      t_eval.h t_eval1.h t_eval3.h t_ml.h t_gmin.h
t_lin.o     : t_lin.c tda.h t_gen.h t_gf.h  
t_lsei.o    : t_lsei.c tda.h t_gen.h 
t_svd.o     : t_svd.c tda.h t_gen.h t_gf.h t_graph.h
t_lp.o      : t_lp.c tda.h t_gen.h         

t_eval.o   : t_eval.c tda.h t_gen.h t_pgen.h t_var.h t_gdat.h t_alloc.h \
	     t_rand.h t_gf.h t_cdf.h t_rzoo.h t_edat.h t_parm.h t_smo.h \
	     t_gmin.h t_int.h t_mat.h t_matf.h t_gcmd.h
t_eval1.o  : t_eval1.c tda.h t_gen.h t_pgen.h t_var.h t_gdat.h t_alloc.h \
	     t_rand.h t_gf.h t_cdf.h t_rzoo.h t_edat.h t_parm.h t_smo.h \
	     t_gmin.h t_int.h t_mat.h t_matf.h t_eval.h t_eval3.h t_mdat.h
t_eval2.o  : t_eval2.c tda.h t_gen.h t_pgen.h t_var.h t_gdat.h t_alloc.h \
	     t_rand.h t_gf.h t_cdf.h t_rzoo.h t_edat.h t_parm.h t_smo.h \
	     t_gmin.h t_int.h t_mat.h t_matf.h t_eval.h t_eval1.h t_eval3.h t_mdat.h
t_eval3.o  : t_eval3.c tda.h t_gen.h t_pgen.h t_var.h t_gdat.h t_alloc.h \
	     t_rand.h t_gf.h t_cdf.h t_rzoo.h t_edat.h t_parm.h t_smo.h \
	     t_gmin.h t_int.h t_mat.h t_matf.h t_eval.h

t_edat.o    : t_edat.c tda.h t_gen.h t_pgen.h t_gdat.h t_freq.h \
	      t_var.h t_parm.h t_alloc.h t_gf.h t_eval.h t_eval1.h
t_ltb.o     : t_ltb.c tda.h t_gen.h t_pgen.h t_parm.h t_edat.h \
	      t_gdat.h t_var.h
t_ple.o     : t_ple.c tda.h t_gen.h t_edat.h t_gdat.h t_parm.h \
	      t_pgen.h t_var.h t_gf.h t_cdf.h t_lsei.h \
	      t_alloc.h
t_rate.o    : t_rate.c tda.h t_gen.h t_pgen.h t_parm.h t_alloc.h  \
	      t_gdat.h t_edat.h t_var.h t_ml.h t_gf.h t_min.h t_cdf.h \
	      t_int.h t_fnrta.h
t_prate.o   : t_prate.c tda.h t_gen.h t_pgen.h t_parm.h t_alloc.h \
	      t_gdat.h t_edat.h t_var.h t_rate.h t_ml.h t_gf.h t_cdf.h \
	      t_int.h t_fnrta.h

t_psf.o     : t_psf.c tda.h t_gen.h t_pgen.h t_parm.h t_plot.h \
	      t_dplot.h t_psinit.h t_cplot.h t_xplot.h      
t_plot.o    : t_plot.c tda.h t_gen.h t_pgen.h t_parm.h t_alloc.h t_gdat.h \
	      t_eval.h t_gf.h  t_spl.h t_int.h t_gmin.h t_graph.h t_var.h \
	      t_areg.h t_sort.h t_ml.h t_eval3.h
t_plg.o     : t_plg.c tda.h t_gen.h t_pgen.h t_parm.h t_alloc.h t_gdat.h \
	      t_gf.h t_plot.h
t_dplot.o   : t_dplot.c tda.h t_gen.h t_pgen.h t_parm.h t_plot.h
t_psinit.o  : t_psinit.c tda.h t_gen.h t_plot.h
t_cplot.o   : t_cplot.c tda.h t_gen.h t_pgen.h t_parm.h t_plot.h t_var.h \
	      t_gdat.h t_eval.h t_gf.h t_gmin.h t_int.h
t_xplot.o   : t_xplot.c tda.h t_gen.h t_pgen.h t_parm.h t_plot.h \
	      t_psinit.h t_psf.h t_var.h t_gdat.h t_sort.h t_alloc.h \
	      t_gf.h t_lsei.h t_l1reg.h t_areg.h t_eval.h t_int.h t_freq.h \
	      t_graph.h t_l1reg.h t_gmin.h
t_gmin.o    : t_gmin.c tda.h t_gen.h t_pgen.h t_parm.h t_ml.h t_tmin.h \
	      t_var.h t_gdat.h t_lsei.h t_cdf.h t_min.h  \
	      t_con.h t_edat.h t_mat.h t_matf.h t_eval.h t_eval1.h t_eval3.h
t_tmin.o    : t_tmin.c tda.h t_gen.h t_pgen.h t_parm.h t_ml.h t_gmin.h \
	      t_gf.h t_mat.h t_matf.h
t_ml.o      : t_ml.c tda.h t_gen.h t_pgen.h t_gf.h t_fnrtb.h t_eval.h \
	      t_fnqr.h t_parm.h t_con.h t_tmin.h t_edat.h \
	      t_rate.h t_fnrta.h t_fnrtc.h t_lin.h t_gmin.h \
	      t_int.h t_mat.h t_matf.h 
t_con.o     : t_con.c tda.h t_gen.h t_pgen.h t_parm.h t_ml.h t_alloc.h \
	      t_lsei.h
t_min.o     : t_min.c tda.h t_gen.h t_gf.h t_ml.h t_svd.h t_gdat.h \
	      t_rand.h t_parm.h t_con.h t_alloc.h t_tmin.h t_int.h
t_fnrta.o   : t_fnrta.c tda.h t_gen.h t_gf.h t_ml.h t_gdat.h t_edat.h \
	      t_rate.h t_parm.h t_eval.h t_eval1.h t_var.h t_cdf.h \
	      t_pgen.h t_lsei.h t_alloc.h t_prate.h t_lin.h t_mat.h t_matf.h
t_fnrtb.o   : t_fnrtb.c tda.h t_gen.h t_gf.h t_ml.h t_gdat.h t_edat.h \
	      t_rate.h t_parm.h t_int.h t_cdf.h t_mat.h t_matf.h
t_fnrtc.o   : t_fnrtc.c tda.h t_gen.h t_gf.h t_ml.h t_gdat.h t_edat.h \
	      t_rate.h t_parm.h t_mat.h t_matf.h

t_seq.o     : t_seq.c tda.h t_gen.h t_pgen.h t_gdat.h t_var.h t_alloc.h \
	      t_rand.h t_gf.h t_parm.h t_seqe.h t_seqm.h
t_seqe.o    : t_seqe.c tda.h t_gen.h t_pgen.h t_gdat.h t_var.h t_alloc.h \
	      t_gf.h t_parm.h t_seq.h
t_seqm.o    : t_seqm.c tda.h t_gen.h t_pgen.h t_parm.h t_seq.h \
	      t_gdat.h t_var.h t_rand.h t_gf.h t_mat.h

t_gdd.o     : t_gdd.c tda.h t_gen.h t_pgen.h t_parm.h t_var.h t_alloc.h \
	      t_gdat.h t_gf.h t_sort.h t_rand.h
t_graph.o   : t_graph.c tda.h t_gen.h t_pgen.h t_parm.h t_var.h t_gdd.h \
	      t_alloc.h t_gdat.h t_sort.h t_gf.h t_ml.h t_rand.h t_gio.h \
	      t_svd.h
t_gio.o     : t_gio.c tda.h t_gen.h t_pgen.h t_parm.h t_var.h t_gdd.h \
	      t_alloc.h t_gdat.h t_sort.h t_ml.h t_gf.h t_gg.h
t_tree.o    : t_tree.c tda.h t_gen.h t_pgen.h t_parm.h t_gdd.h  \
	      t_alloc.h t_plot.h
t_gg.o      : t_gg.c tda.h t_gen.h t_pgen.h t_parm.h t_var.h t_gdd.h \
	      t_alloc.h t_gdat.h t_sort.h t_ml.h t_gf.h t_gio.h t_com.h
t_prox.o    : t_prox.c tda.h t_gen.h t_pgen.h t_parm.h t_var.h t_gdd.h \
	      t_alloc.h t_gdat.h t_sort.h t_gf.h t_gio.h \
	      t_mat.h t_matc.h t_svd.h
t_cl.o      : t_cl.c tda.h t_gen.h t_pgen.h t_parm.h t_var.h t_gdd.h \
	      t_alloc.h t_gdat.h t_sort.h t_gf.h t_gio.h
t_mds.o     : t_mds.c tda.h t_gen.h t_pgen.h t_parm.h t_var.h t_gdd.h \
	      t_alloc.h t_gdat.h t_sort.h t_gf.h t_gio.h t_ml.h t_rand.h
t_ass.o     : t_ass.c tda.h t_gen.h t_pgen.h t_parm.h t_var.h t_gdd.h \
	      t_alloc.h t_gdat.h t_sort.h t_gf.h t_gio.h t_ml.h
t_com.o     : t_com.c tda.h t_gen.h t_pgen.h t_parm.h t_gf.h t_alloc.h

t_loglin.o  : t_loglin.c tda.h t_gen.h t_pgen.h t_parm.h t_ml.h t_gdat.h \
	      t_alloc.h t_var.h t_gf.h t_cdf.h t_freq.h t_con.h 
t_mes.o     : t_mes.c tda.h t_gen.h t_pgen.h t_parm.h t_var.h t_gdd.h \
	      t_alloc.h t_gdat.h t_sort.h t_gf.h t_freq.h t_ml.h t_lsei.h
t_dem.o     : t_dem.c tda.h t_gen.h t_pgen.h t_parm.h t_gdat.h t_gf.h \
	      t_ml.h t_alloc.h t_mat.h t_matc.h t_svd.h

