CC = wcc386     
CFLAGS = /j -bt=nt -oaxt -d2 -w4 -i=$(%WATCOM)\h;$(%WATCOM)\h\nt                
#CFLAGS = /j /bt=nt -w4 -i=$(%WATCOM)\h;$(%WATCOM)\h\nt                 

name = tdaw
LNK = tdaw.lnk          
OBJS = tdaw.obj tdaw_pr.obj &
	t_cmd.obj t_gen.obj t_rep.obj t_help.obj &
	t_eval.obj t_eval1.obj t_eval2.obj t_eval3.obj t_brr.obj &
	t_rand.obj t_gf.obj t_cdf.obj t_gdf.obj t_loglin.obj &
	t_parm.obj t_pgen.obj t_alloc.obj t_sort.obj t_con.obj t_gcmd.obj &
	t_dmu.obj t_int.obj &
	t_gdat.obj t_var.obj t_mdat.obj t_pdat.obj &
	t_rzoo.obj t_zoo.obj t_spss.obj t_stata.obj  &
	t_dstat.obj t_ds.obj t_freq.obj t_spl.obj t_smo.obj t_dens.obj t_ineq.obj &
	t_lsreg.obj t_l1reg.obj t_areg.obj t_glm.obj t_nlreg.obj &
	t_mat.obj t_matc.obj t_matf.obj t_svd.obj t_lin.obj t_lsei.obj &
	t_imat.obj &
	t_lp.obj t_qrmod.obj t_fnqr.obj &
	t_gmin.obj t_tmin.obj t_ml.obj t_min.obj  &
	t_edat.obj t_ltb.obj t_ple.obj &
	t_rate.obj t_prate.obj t_fnrta.obj t_fnrtb.obj t_fnrtc.obj &
	t_seq.obj t_seqe.obj t_seqm.obj  &
	t_psf.obj t_plot.obj t_dplot.obj t_psinit.obj t_cplot.obj &
	t_plg.obj t_xplot.obj &
	t_gdd.obj t_graph.obj t_gio.obj t_tree.obj t_gg.obj t_prox.obj t_cl.obj &
	t_mds.obj t_com.obj t_ass.obj t_mes.obj t_dem.obj 



tdaw.exe : $(OBJS) tdaw.res $(LNK)
    wlink @$(LNK)
    @%make bindit

tdaw.res : tdaw.rc $(resources)
    wrc -r -i=.. -fo=.\tdaw.res -bt=nt $[@ 

.c.obj :
	$(CC) $(CFLAGS) $[*
	
linkit : .PROCEDURE
    
bindit : .PROCEDURE
    wrc tdaw.res

# dependencies

.NOCHECK
tdaw.obj : tdaw.c tdaw.h t_cmd.h t_gen.h t_var.h t_mat.h t_eval.h t_rep.h t_gcmd.h &
	     t_help.h t_mdat.h t_gcmd.h
tdaw_pr.obj : tdaw_pr.c tdaw.h t_cmd.h t_gen.h t_var.h t_mat.h t_eval.h t_rep.h t_gcmd.h &
	      t_mdat.h t_gcmd.h
t_cmd.obj     : t_cmd.c tda.h t_gen.h t_pgen.h t_var.h t_gdat.h t_gcmd.h &
	      t_mat.h t_matf.h t_dmu.h t_mdat.h t_pdat.h t_rzoo.h t_spss.h &
	      t_stata.h t_psf.h t_lsreg.h t_l1reg.h t_qrmod.h t_dem.h &
	      t_edat.h t_ltb.h t_ple.h t_rate.h t_seq.h t_gmin.h t_int.h &
	      t_dstat.h t_ineq.h t_eval.h t_eval3.h t_dplot.h  t_plg.h t_smo.h &
	      t_glm.h t_gdd.h t_graph.h t_gio.h t_tree.h t_nlreg.h t_loglin.h &
	      t_xplot.h t_rep.h t_help.h t_gf.h t_brr.h t_gdf.h &
	      t_gg.h t_com.h t_prox.h t_cl.h t_mds.h t_ass.h t_imat.h t_mes.h
t_help.obj    : t_help.c tda.h t_gen.h t_gf.h t_pgen.h
t_rep.obj     : t_rep.c tda.h t_cmd.h t_gen.h t_pgen.h t_parm.h t_alloc.h &
	      t_var.h t_mat.h t_matf.h t_matc.h t_gf.h
t_dmu.obj     : t_dmu.c tda.h t_gen.h t_pgen.h t_parm.h t_alloc.h &
	      t_freq.h t_gdat.h t_gf.h t_sort.h
t_gcmd.obj    : t_gcmd.c tda.h t_gen.h t_pgen.h t_parm.h t_eval.h t_gdat.h &
	      t_gf.h t_var.h 
t_sort.obj    : t_sort.c tda.h t_gen.h t_pgen.h t_parm.h t_gdat.h t_var.h
t_parm.obj    : t_parm.c tda.h t_gen.h t_pgen.h t_var.h t_gmin.h t_gdat.h &
	      t_alloc.h t_eval.h t_plot.h t_ml.h t_mat.h t_rand.h t_imat.h &
	      t_gf.h
t_pgen.obj    : t_pgen.c tda.h t_gen.h t_parm.h t_gdat.h t_eval.h t_eval1.h &
	      t_var.h t_cdf.h t_qrmod.h t_gf.h 
t_alloc.obj   : t_alloc.c tda.h t_gen.h t_pgen.h t_parm.h
t_gen.obj     : t_gen.c tda.h t_var.h
t_int.obj     : t_int.c tda.h t_gen.h t_pgen.h t_parm.h t_alloc.h  &
	      t_gmin.h t_fnrtb.h t_gf.h t_eval.h t_eval3.h
t_rand.obj    : t_rand.c tda.h t_gen.h t_pgen.h t_lin.h
t_gf.obj      : t_gf.c tda.h t_gen.h
t_brr.obj     : t_brr.c tda.h t_gen.h t_pgen.h t_gf.h t_alloc.h t_parm.h
t_cdf.obj     : t_cdf.c tda.h t_gen.h t_gf.h t_lin.h

t_var.obj     : t_var.c tda.h t_gen.h t_pgen.h t_eval.h t_gdat.h t_eval2.h &
	      t_parm.h t_gf.h t_alloc.h t_freq.h t_mdat.h t_eval3.h t_mat.h
t_gdat.obj    : t_gdat.c tda.h t_gen.h t_pgen.h t_parm.h t_var.h &
	      t_gf.h t_zoo.h t_rzoo.h t_sort.h t_mdat.h t_pdat.h t_alloc.h &
	      t_rand.h t_eval.h t_eval1.h t_eval2.h t_eval3.h
t_mdat.obj    : t_mdat.c tda.h t_gen.h t_pgen.h t_parm.h t_gdat.h &
	      t_var.h t_gf.h t_edat.h t_seq.h t_alloc.h t_gdd.h t_matf.h &
	      t_eval.h t_eval1.h t_mat.h t_matc.h t_rzoo.h
t_rzoo.obj    : t_rzoo.c tda.h t_gen.h t_pgen.h t_parm.h t_zoo.h t_var.h &
	      t_gdat.h t_alloc.h t_gf.h
t_zoo.obj     : t_zoo.c tda.h t_gen.h t_rzoo.h
t_spss.obj    : t_spss.c tda.h t_gen.h t_pgen.h t_parm.h t_sort.h t_var.h &
	      t_gdat.h t_alloc.h t_eval.h t_eval1.h t_gf.h
t_stata.obj   : t_stata.c tda.h t_gen.h t_pgen.h t_var.h t_gdat.h t_parm.h &
	      t_alloc.h t_sort.h t_eval.h t_eval1.h t_gf.h t_spss.h
t_pdat.obj    : t_pdat.c tda.h t_gen.h t_pgen.h t_parm.h t_gdat.h &
	      t_var.h t_gf.h t_alloc.h t_sort.h

t_dstat.obj   : t_dstat.c tda.h t_gen.h t_pgen.h t_parm.h t_alloc.h  &
	      t_gdat.h t_var.h t_ds.h t_sort.h t_freq.h t_gf.h t_cdf.h &
	      t_matf.h t_svd.h
t_ds.obj      : t_ds.c tda.h t_gen.h t_pgen.h t_parm.h t_alloc.h &
	      t_var.h t_gdat.h t_sort.h t_cdf.h  
t_freq.obj    : t_freq.c tda.h t_gen.h t_pgen.h t_gdat.h
t_ineq.obj    : t_ineq.c tda.h t_gen.h t_pgen.h t_parm.h t_gdat.h t_alloc.h &
	      t_var.h t_ds.h t_matf.h
t_dens.obj    : t_dens.c tda.h t_gen.h t_pgen.h t_parm.h t_gdat.h &
	      t_var.h t_plot.h t_alloc.h t_cdf.h
t_smo.obj     : t_smo.c tda.h t_gen.h t_pgen.h t_parm.h t_alloc.h &
	      t_gdat.h t_var.h t_spl.h t_sort.h t_ml.h t_gf.h t_areg.h &
	      t_plot.h
t_spl.obj     : t_spl.c tda.h t_gen.h          

t_gdf.obj     : t_gdf.c tda.h t_gen.h t_pgen.h t_parm.h t_alloc.h t_svd.h &
	      t_gdat.h t_var.h t_con.h t_cdf.h t_lsei.h t_mat.h t_sort.h &
	      t_ml.h t_gf.h t_freq.h
t_lsreg.obj   : t_lsreg.c tda.h t_gen.h t_pgen.h t_parm.h t_alloc.h t_svd.h &
	      t_gdat.h t_var.h t_con.h t_cdf.h t_lsei.h t_mat.h t_sort.h &
	      t_ml.h t_gf.h t_freq.h t_matf.h
t_l1reg.obj   : t_l1reg.c tda.h t_gen.h t_pgen.h t_alloc.h t_var.h t_gdat.h &
	      t_parm.h t_gf.h t_sort.h t_lsei.h t_mat.h t_matf.h
t_areg.obj    : t_areg.c tda.h t_gen.h t_pgen.h t_parm.h t_alloc.h t_gdat.h &
	      t_var.h t_sort.h t_ds.h t_smo.h t_gf.h
t_nlreg.obj    : t_nlreg.c tda.h t_gen.h t_pgen.h t_parm.h t_gdat.h t_eval.h &
	      t_alloc.h t_ml.h t_gf.h t_var.h t_lin.h t_cdf.h t_eval3.h
t_glm.obj     : t_glm.c tda.h t_gen.h t_pgen.h t_parm.h t_gdat.h t_eval.h &
	      t_alloc.h t_ml.h t_gmin.h t_lsei.h t_gf.h t_var.h t_con.h &
	      t_cdf.h t_eval3.h
t_qrmod.obj   : t_qrmod.c tda.h t_gen.h t_pgen.h t_parm.h t_gdat.h t_freq.h &
	      t_ml.h t_gf.h t_var.h t_cdf.h t_con.h t_alloc.h &
	      t_sort.h t_min.h t_fnqr.h
t_fnqr.obj    : t_fnqr.c tda.h t_gen.h t_gdat.h t_qrmod.h t_ml.h &
	      t_gf.h t_cdf.h t_lin.h t_int.h t_parm.h t_mat.h t_matf.h

t_mat.obj     : t_mat.c tda.h t_gen.h t_var.h t_gdat.h t_matf.h t_gcmd.h &
	      t_pgen.h t_parm.h t_gf.h t_alloc.h t_matc.h t_imat.h t_gdd.h &
	      t_mdat.h
t_matc.obj    : t_matc.c tda.h t_gen.h t_var.h t_gdat.h t_svd.h t_eval.h &
	      t_lin.h t_lsei.h t_lp.h t_pgen.h t_parm.h t_gf.h t_alloc.h &
	      t_mat.h t_matf.h t_sort.h t_brr.h
t_matf.obj    : t_matf.c tda.h t_gen.h t_var.h t_gdat.h t_svd.h  &
	      t_lin.h t_lsei.h t_lp.h t_pgen.h t_parm.h t_gf.h t_alloc.h &
	      t_mat.h t_eval.h t_eval1.h t_eval2.h
t_imat.obj    : t_imat.c tda.h t_gen.h t_var.h t_gdat.h t_mat.h t_matf.h  &
	      t_pgen.h t_parm.h t_gf.h t_alloc.h t_matc.h t_sort.h &
	      t_eval.h t_eval1.h t_eval3.h t_ml.h t_gmin.h
t_lin.obj     : t_lin.c tda.h t_gen.h t_gf.h  
t_lsei.obj    : t_lsei.c tda.h t_gen.h 
t_svd.obj     : t_svd.c tda.h t_gen.h t_gf.h t_graph.h
t_lp.obj      : t_lp.c tda.h t_gen.h         

t_eval.obj   : t_eval.c tda.h t_gen.h t_pgen.h t_var.h t_gdat.h t_alloc.h &
	     t_rand.h t_gf.h t_cdf.h t_rzoo.h t_edat.h t_parm.h t_smo.h &
	     t_gmin.h t_int.h t_mat.h t_matf.h t_gcmd.h
t_eval1.obj  : t_eval1.c tda.h t_gen.h t_pgen.h t_var.h t_gdat.h t_alloc.h &
	     t_rand.h t_gf.h t_cdf.h t_rzoo.h t_edat.h t_parm.h t_smo.h &
	     t_gmin.h t_int.h t_mat.h t_matf.h t_eval.h t_eval3.h t_mdat.h
t_eval2.obj  : t_eval2.c tda.h t_gen.h t_pgen.h t_var.h t_gdat.h t_alloc.h &
	     t_rand.h t_gf.h t_cdf.h t_rzoo.h t_edat.h t_parm.h t_smo.h &
	     t_gmin.h t_int.h t_mat.h t_matf.h t_eval.h t_eval1.h t_eval3.h t_mdat.h
t_eval3.obj  : t_eval3.c tda.h t_gen.h t_pgen.h t_var.h t_gdat.h t_alloc.h &
	     t_rand.h t_gf.h t_cdf.h t_rzoo.h t_edat.h t_parm.h t_smo.h &
	     t_gmin.h t_int.h t_mat.h t_matf.h t_eval.h

t_edat.obj    : t_edat.c tda.h t_gen.h t_pgen.h t_gdat.h t_freq.h &
	      t_var.h t_parm.h t_alloc.h t_gf.h t_eval.h t_eval1.h
t_ltb.obj     : t_ltb.c tda.h t_gen.h t_pgen.h t_parm.h t_edat.h &
	      t_gdat.h t_var.h
t_ple.obj     : t_ple.c tda.h t_gen.h t_edat.h t_gdat.h t_parm.h &
	      t_pgen.h t_var.h t_gf.h t_cdf.h t_lsei.h &
	      t_alloc.h
t_rate.obj    : t_rate.c tda.h t_gen.h t_pgen.h t_parm.h t_alloc.h  &
	      t_gdat.h t_edat.h t_var.h t_ml.h t_gf.h t_min.h t_cdf.h &
	      t_int.h t_fnrta.h
t_prate.obj   : t_prate.c tda.h t_gen.h t_pgen.h t_parm.h t_alloc.h &
	      t_gdat.h t_edat.h t_var.h t_rate.h t_ml.h t_gf.h t_cdf.h &
	      t_int.h t_fnrta.h

t_psf.obj     : t_psf.c tda.h t_gen.h t_pgen.h t_parm.h t_plot.h &
	      t_dplot.h t_psinit.h t_cplot.h t_xplot.h      
t_plot.obj    : t_plot.c tda.h t_gen.h t_pgen.h t_parm.h t_alloc.h t_gdat.h &
	      t_eval.h t_gf.h  t_spl.h t_int.h t_gmin.h t_graph.h t_var.h &
	      t_areg.h t_sort.h t_ml.h t_eval3.h
t_plg.obj     : t_plg.c tda.h t_gen.h t_pgen.h t_parm.h t_alloc.h t_gdat.h &
	      t_gf.h t_plot.h
t_dplot.obj   : t_dplot.c tda.h t_gen.h t_pgen.h t_parm.h t_plot.h
t_psinit.obj  : t_psinit.c tda.h t_gen.h t_plot.h
t_cplot.obj   : t_cplot.c tda.h t_gen.h t_pgen.h t_parm.h t_plot.h t_var.h &
	      t_gdat.h t_eval.h t_gf.h t_gmin.h t_int.h
t_xplot.obj   : t_xplot.c tda.h t_gen.h t_pgen.h t_parm.h t_plot.h &
	      t_psinit.h t_psf.h t_var.h t_gdat.h t_sort.h t_alloc.h &
	      t_gf.h t_lsei.h t_l1reg.h t_areg.h t_eval.h t_int.h t_freq.h &
	      t_graph.h t_l1reg.h t_gmin.h
t_gmin.obj    : t_gmin.c tda.h t_gen.h t_pgen.h t_parm.h t_ml.h t_tmin.h &
	      t_var.h t_gdat.h t_lsei.h t_cdf.h t_min.h  &
	      t_con.h t_edat.h t_mat.h t_matf.h t_eval.h t_eval1.h t_eval3.h
t_tmin.obj    : t_tmin.c tda.h t_gen.h t_pgen.h t_parm.h t_ml.h t_gmin.h &
	      t_gf.h t_mat.h t_matf.h
t_ml.obj      : t_ml.c tda.h t_gen.h t_pgen.h t_gf.h t_fnrtb.h t_eval.h &
	      t_fnqr.h t_parm.h t_con.h t_tmin.h t_edat.h &
	      t_rate.h t_fnrta.h t_fnrtc.h t_lin.h t_gmin.h &
	      t_int.h t_mat.h t_matf.h 
t_con.obj     : t_con.c tda.h t_gen.h t_pgen.h t_parm.h t_ml.h t_alloc.h &
	      t_lsei.h
t_min.obj     : t_min.c tda.h t_gen.h t_gf.h t_ml.h t_svd.h t_gdat.h &
	      t_rand.h t_parm.h t_con.h t_alloc.h t_tmin.h t_int.h
t_fnrta.obj   : t_fnrta.c tda.h t_gen.h t_gf.h t_ml.h t_gdat.h t_edat.h &
	      t_rate.h t_parm.h t_eval.h t_eval1.h t_var.h t_cdf.h &
	      t_pgen.h t_lsei.h t_alloc.h t_prate.h t_lin.h t_mat.h t_matf.h
t_fnrtb.obj   : t_fnrtb.c tda.h t_gen.h t_gf.h t_ml.h t_gdat.h t_edat.h &
	      t_rate.h t_parm.h t_int.h t_cdf.h t_mat.h t_matf.h
t_fnrtc.obj   : t_fnrtc.c tda.h t_gen.h t_gf.h t_ml.h t_gdat.h t_edat.h &
	      t_rate.h t_parm.h t_mat.h t_matf.h

t_seq.obj     : t_seq.c tda.h t_gen.h t_pgen.h t_gdat.h t_var.h t_alloc.h &
	      t_rand.h t_gf.h t_parm.h t_seqe.h t_seqm.h
t_seqe.obj    : t_seqe.c tda.h t_gen.h t_pgen.h t_gdat.h t_var.h t_alloc.h &
	      t_gf.h t_parm.h t_seq.h
t_seqm.obj    : t_seqm.c tda.h t_gen.h t_pgen.h t_parm.h t_seq.h &
	      t_gdat.h t_var.h t_rand.h t_gf.h t_mat.h

t_gdd.obj     : t_gdd.c tda.h t_gen.h t_pgen.h t_parm.h t_var.h t_alloc.h &
	      t_gdat.h t_gf.h t_sort.h t_rand.h
t_graph.obj   : t_graph.c tda.h t_gen.h t_pgen.h t_parm.h t_var.h t_gdd.h &
	      t_alloc.h t_gdat.h t_sort.h t_gf.h t_ml.h t_rand.h t_gio.h &
	      t_svd.h
t_gio.obj     : t_gio.c tda.h t_gen.h t_pgen.h t_parm.h t_var.h t_gdd.h &
	      t_alloc.h t_gdat.h t_sort.h t_ml.h t_gf.h t_gg.h
t_tree.obj    : t_tree.c tda.h t_gen.h t_pgen.h t_parm.h t_gdd.h  &
	      t_alloc.h t_plot.h
t_gg.obj      : t_gg.c tda.h t_gen.h t_pgen.h t_parm.h t_var.h t_gdd.h &
	      t_alloc.h t_gdat.h t_sort.h t_ml.h t_gf.h t_gio.h t_com.h
t_prox.obj    : t_prox.c tda.h t_gen.h t_pgen.h t_parm.h t_var.h t_gdd.h &
	      t_alloc.h t_gdat.h t_sort.h t_gf.h t_gio.h &
	      t_mat.h t_matc.h t_svd.h
t_cl.obj      : t_cl.c tda.h t_gen.h t_pgen.h t_parm.h t_var.h t_gdd.h &
	      t_alloc.h t_gdat.h t_sort.h t_gf.h t_gio.h
t_mds.obj     : t_mds.c tda.h t_gen.h t_pgen.h t_parm.h t_var.h t_gdd.h &
	      t_alloc.h t_gdat.h t_sort.h t_gf.h t_gio.h t_ml.h t_rand.h
t_ass.obj     : t_ass.c tda.h t_gen.h t_pgen.h t_parm.h t_var.h t_gdd.h &
	      t_alloc.h t_gdat.h t_sort.h t_gf.h t_gio.h t_ml.h
t_com.obj     : t_com.c tda.h t_gen.h t_pgen.h t_parm.h t_gf.h t_alloc.h

t_loglin.obj  : t_loglin.c tda.h t_gen.h t_pgen.h t_parm.h t_ml.h t_gdat.h &
	      t_alloc.h t_var.h t_gf.h t_cdf.h t_freq.h t_con.h 
t_mes.obj     : t_mes.c tda.h t_gen.h t_pgen.h t_parm.h t_var.h t_gdd.h &
	      t_alloc.h t_gdat.h t_sort.h t_gf.h t_freq.h t_ml.h t_lsei.h
t_dem.obj     : t_dem.c tda.h t_gen.h t_pgen.h t_parm.h t_gdat.h t_gf.h &
	      t_ml.h t_alloc.h t_mat.h t_matc.h t_svd.h
##t_xlib.obj    : t_xlib.c
